### ISSUE TITLE
Command bar and plugins are not supported in sub-window or split windows

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#181] opened 2022-01-08 21:05 UTC
Plugin commands aren't working on sub-windows even when frontmost.

**Comment by EduardMe** [comment] 2022-01-10 22:51
Is this working now or is it wrongly in the Done column?

**Comment by jgclark** [comment] 2022-01-10 23:38
When I checked yesterday, it wasn't done. If you haven't worked on it, @EduardMe, it can't be done!

**Comment by jgclark** [comment] 2022-01-12 15:27
Moving it back to To do.

**Comment by EduardMe** [comment] 2022-01-20 15:16
Fixed it and should be available in the next update. We can close it once confirmed.

**Comment by jgclark** [comment] 2022-01-29 20:12
Confirmed this has been fixed. Thank you.

**Comment by jgclark** [comment] 2022-02-03 13:17
Re-opening this, as I've now found that the older separate sub-windows still don't work with command bar or plugins.

**Comment by EduardMe** [comment] 2022-02-03 14:50
Thanks, can you let me know which plugin you have tried. I tested it with a few plugins, like /wc and /time to see if the editor is being targeted and it worked and still works for me:

![2022-02-03 09 49 27](https://user-images.githubusercontent.com/3285090/152366295-cd4e5ccc-8f7b-41c9-9c96-155b1f357881.gif)

**Comment by jgclark** [comment] 2022-02-03 18:24
/wc and /jump to heading and /time ...
They don't work when run from command bar. They do work when run inline as a slash-command in the editor.

**Comment by EduardMe** [comment] 2022-02-07 00:34
Did you give the new window cursor focus? Means clicked into the text? Because I can definitely use it on a new window. With the command bar. The gif I posted above shows it. Am I reproducing it incorrectly? @dwertheimer @mikeerickson what do you see?

**Comment by jgclark** [comment] 2022-02-07 17:19
I can't tell from your gif above whether this is the main and/or only window or not.
Here's an example from me using /rpt on the secondary window, but it working on the main window (and therefore not finding anything):

https://user-images.githubusercontent.com/1671754/152838641-6cf2bb25-2642-483c-9028-12ef2b4383a5.mov

Note also which window gets focus after I click on the dialog: the main window not the secondary window.

**Comment by dwertheimer** [comment] 2022-02-07 17:45
Ah, so it seems that from the API POV, calling Editor references only the
main doc, not the floating window. Wonder what happens with multiple panes
as well.

**Comment by jgclark** [comment] 2022-02-07 23:21
> Ah, so it seems that from the API POV, calling Editor references only the main doc, not the floating window.

That's helpful analysis, thanks.

> Wonder what happens with multiple panes as well.

It's OK with multiple panes -- which is why I initially closed this issue.

**Comment by EduardMe** [comment] 2022-02-07 23:54
Ok, it's a mystery for me, everything checks out as expected. I must be doing something completely different, here's a video: https://www.loom.com/share/602e790a037c4cf49514d8ab7a0bfd44

Let me know what I'm doing wrong!

**Comment by EduardMe** [comment] 2022-02-08 00:02
And just to be sure, I also tried /rpt:

![2022-02-07 19 01 32](https://user-images.githubusercontent.com/3285090/152892480-6371ffa7-91c8-4927-b802-fe4d13fb6919.gif)

**Comment by jgclark** [comment] 2022-02-19 22:20
This is still not working for sub-windows for me in 3.4.1 beta.
It is working in split windows, though.

**Closed** 2022-06-28 20:34 UTC
Labels: bug, high
