### ISSUE TITLE
EventsHelper new meeting note behavior

### ISSUE THREAD

**Issue by chrisortman** [NotePlan/plugins#491] opened 2023-09-29 19:30 UTC
**Describe the bug**
I am using the `*|MEETINGNOTE|*` text expansion in the events list generated by `/insert`. When I click the link, I am prompted for a template to use and asked where to create the note. If I do this for a recurring meeting, sometimes it will pick the date of the first occurrence of the meeting series rather than the date of the day of the daily note where I cam clicking the link.

**To Reproduce**
1. Create recurring meeting starting some time in the past on your calendar
2. Setup a meeting note template that includes the event date
3. Move to a daily note for 1 day in the future
4. insert the days events as list and include `*|MEETINGNOTE|*`
5. Look at the date in the note, is it the start of the series or the day of the meeting?

**Expected behavior**
Expect the eventDate to be the day the meeting is on which corresponds to the daily note where the link is clicked.

**Screenshots**

**System**
 - Device: macOS 
 - OS: macOS 13.5.2
 - NotePlan Version 3.9.7
 - Plugin Name & Version EventHelpers v0.20.3

**Additional context**

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin's Preferences by going to `NotePlan's menu > Preferences > Plugins` and clicking the settings "cog" icon next to the plugin in question. Scroll to the bottom and set the logging level to "DEBUG" and click "Save & Close"
7. Now open the Plugin Console by going to `Noteplan > Help > Plugin Console`
8. Run the plugin command you're reporting
9. Copy the output from the Plugin Console and paste it below
10. Delete any output that has personal information you don't want in there
```javascript
    PASTE_PLUGIN_CONSOLE_OUTPUT_HERE
```

**Comment by dwertheimer** [comment] 2023-09-29 22:42
This is an interesting question. On one hand, you might say this is a feature, not a bug. Bear with me while I explain:

I don't see any information in the calendar item details that we can use to get today's occurrence of this item from the API. For example, here's a recurring calendar item I set up 3 years ago that recurs daily:

```js
{
  "id": "29B622E3-FA1D-449D-80F7-AF9E353A592A",
  "title": "Personal Items/Tiller/Bills",
  "date": "2020-02-06T18:30:00.000Z",
  "endDate": "2020-02-06T19:00:00.000Z",
  "type": "event",
  "isAllDay": false,
  "isCompleted": false,
  "occurences": [
    "2020-02-06T07:00:00.000Z"
  ],
  "calendar": "David",
  "calendarID": "EAC69878-D7A8-4794-AD15-A6359E9F6DC4",
  "notes": "",
  "url": "",
  "availability": 1,
  "attendees": [],
  "attendeeNames": [],
  "calendarItemLink": "![📅](2020-02-06 11:30:::9ggf3japoi7pvarovd8bduo4f8@google.com:::NA:::!Personal Items/Tiller/Bills!:::#1BADF8)",
  "location": "",
  "isCalendarWritable": true,
  "isRecurring": true
}
``` 
So, unless @EduardMe has a field that he can add to deliver the today version of this item, we may have to find a work-around. Seems to me there are a couple of ways to get what you want by simply editing your meeting template:

1. Use today's date for the meeting note
Here is the Default Meeting Note template that I use to create all my meeting notes. Since I only take meeting notes on the day of the meeting, this version works great for me:
```
---
title: Default Meeting Note (today version)
newNoteTitle: <%- eventTitle %> - <%- date8601() %>
folder: <select>
type: meeting-note
---
> <%- calendarItemLink %> <%- eventLocation %> <%- eventLink %> <%- eventNotes %>
**Attendees:** <%- eventAttendeeNames %>
```
This results in a note titled something like `Meeting with Chris - 2023-09-29"
I am not using the date of the calendar item at all. The fact that I created the note for today was enough.

2. You could use the date of the calendar note you are actually on when you click to create the meeting note. This would be useful for people who plan the day before or the week before or whatever. List that day's events in the note, click the link and use a slightly different template to create the date:

```
---
title: Default Meeting Note (open note in editor version)
newNoteTitle: <%- eventTitle %> - <%- date.format('YYYY-MM-DD',Editor.note.title) %>
folder: <select>
type: meeting-note
---
> <%- calendarItemLink %> <%- eventLocation %> <%- eventLink %> <%- eventNotes %>
**Attendees:** <%- eventAttendeeNames %>
```
As you can probably see, this one just reads the open note currently in the Editor's title (which is the date) and uses it to calculate the date. Now that I typed all this out, I think this second version would be the best version to use, because it would always work for my use case when I'm on today's date, but if I ever did want to click it for a day in the past, present, future, it would work also. So thank you @chrisortman you have led to an improved solution for all of us.

3. As a bonus (you didn't ask about this), we are soon going to release an update to the MeetingNotes plugin which will actually take advantage of the fact that this is a recurring calendar item. For example, maybe you like to have a single meeting note for this recurring calendar item (e.g. staff meeting), and when you click, you want the ability to open up that one single note every day/week/month whatever. In that case, you would *not* include any date in the title of the meeting note template and simply use the event title, so you can bring up the same note by clicking the MEETINGNOTE link. Your template would look something like:
```
---
title: Default Recurring Meeting Note (today's notes at the top)
prepend: <%- eventTitle %>
note: The above prepend could have said append to put the new notes at the bottom
type: meeting-note
---
## <%- date8601() %>

```
This would result in a running notes document that looks like:
<img width="319" alt="Screen Cap 2023-09-29 at 16 36 24@2x" src="https://github.com/NotePlan/plugins/assets/8949588/682e60b3-e72f-45db-b00a-8cec027a4fa8">

@chrisortman let me know if this answered your question. I'm closing this ticket presuming so.
cc @jgclark

**Closed by dwertheimer** 2023-09-29 22:42 UTC
