### ISSUE TITLE
Notes not updating when plugin command started inline

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#274] opened 2022-05-04 21:54 UTC
I knew there was an issue with at least one of the API calls, but I've only now been able to isolate it, with a prompt from @george65. He reported that the `/process date offsets` command works fine when run from menu or command bar, but doesn't if you type the command inline in a note. Nothing happens ... but weirdly the logging was showing just the same correct output in both cases.

But it turns out that the note **was** updated OK, but the note content didn't refresh.  Switch to another note and then back to the note, and the results of the command are then showing.  

I _think_ it's probably to do with `updateParagraph(...)` calls. It doesn't seem to matter whether this is used as `Editor.updateParagraph` or `note.updateParagraph`.

You can test it on my note https://noteplan.co/n/E35AE9F3-8A28-4284-88C5-6940D2FA21E3.

**Comment by mcolacino57** [comment] 2022-05-07 21:11
I have a similar problem with my code in the sense that updateParagraph seems to have some significant latency. My use case is to a) rename a note and b) move it to another part of the folder hierachy based upon the renaming. The renaming code works and the relocation code works, but if you put the together they fail by "losing" the renaming. Putting a prompt or a several-second delay between makes it work, but this is a bug and makes me reluctant to spend much time on code I have in mind. There has to be some workaround for this that the plug-in developers use to do multi-step actions, but I haven't been able to find it in the plugin repost. Happy to provide my code for illustration.

**Comment by dwertheimer** [comment] 2022-05-07 21:46
Yes pls provide code. Maybe we will have ideas. Great to have u developing!

**Comment by mcolacino57** [comment] 2022-05-09 18:18
Here is my code. It does two things. First asks the user to enter a prefix (for example ’39.14’) and then it sticks the prefix at the front of the note’s title. This works fine.

The second thing it does is to look among the folders to see if there is one with this prefix, with the goal of moving the note into that folder. This also works fine when run as a standalone snippet.

The problem occurs when you combine them. The directory move happens but the name reverts to its prior state, i.e. doesn’t get updated.

Commentary: if I put something in between the updateParagraph and the moveNote (say a user prompt) then it works properly. Also if I put a delay loop in there of a few seconds it works. It might be that the updateParagraph is not waiting to fully complete and therefore returns in a partial state that is then un-set by the moveNote.

As I have mentioned in a prior email to Eduard, this seems like a very generic use-case despite the fact that I am using it in a special way. If you can’t update a title and then move a note without chewing cycles in between, this seems limiting to me.

Just for background my plugin purpose is to implement a version of the Johnny Decimal naming system on top of Noteplan. I have found that despite what tools I use, there is difficulty retrieving information across platforms (say from Dropbox to Craft to Roam to Noteplan to Email). Rather than having one system to rule them all, the Johnny Decimal system uses a naming convention that works in any file system and allows you to link across platforms. Here is the link: https://johnnydecimal.com/



async function combinedTest() {
  try {

    var prefix = await CommandBar.showInput("Enter prefix", "Create a prefix = '%@'");
    prefix = prefix + " ";
    const para = Editor.paragraphs;
    para[0].content = prefix + para[0].content;
    Editor.updateParagraph(para[0]);
    // Editor.updateParagraphs(para); tried this also; doesn't work
    console.log(`para zero: is ${para[0].content}`)
    var filename = Editor.filename; // Actual filename as in Finder
    console.log(`filename is ${filename}`)
    var allFolders = DataStore.folders;
    var foundDestFolder = allFolders.find(f => f.includes(prefix));
    console.log(`dest folder is ${foundDestFolder}`)
    await DataStore.moveNote(filename, foundDestFolder);

  } catch (err) {
    console.log(`Error: ${err}`);
  }



Michael Colacino
917-664-4787
***@***.***

**Comment by EduardMe** [comment] 2022-05-11 22:38
Hi Michael,

Sorry for my late replies on this. I think I have sent you just yesterday
an email with the fixed code.

Basically, swap the `Editor` object with `Note`. You get the note object
using `Editor.note` and it has the same paragraph calls you have used so
far. What it does is that it writes the changes you apply to the paragraph
immediately into the file. `Editor`, on the other hand, doesn't do this for
performance reasons. So you are moving the note before the Editor finished
saving the file and it creates an odd situation.

Let us know if this works better for you. See your mailbox for the complete
code to copy & paste, which worked on my side.

**Comment by dwertheimer** [comment] 2022-05-11 23:16
@eduardme This seems to relate to the slash-command race condition I
emailed you about. Seems to me that CMD-J or a slash command should
immediately flush the cache and write the Editor to disk on before plugin
startup and should refresh the editor on plugin complete. This situation
will come up again and again if not addressed in a generalized manner.

**Comment by EduardMe** [comment] 2022-05-11 23:41
It's not before the plugin starts, but after every change in this case.
Like when you update the paragraph, it's not yet written to disc. But even
if this happens, its still not cached yet. The cache gets notified after
the file gets changed, waits for a little to collect more notifications,
and then applies the changes all async. So saving the Editor's content
before launching a plugin is also not solving this issue. However, if you
read out the text from the Editor directly, you always got the most
up-to-date content.

But we could maybe add a function `await Editor.save()`?

**Comment by jgclark** [comment] 2022-05-23 22:24
I confess I lost track of whether the discussion was likely to address my initial report. Could I ask for an update please, @EduardMe?

**Comment by jgclark** [comment] 2022-06-22 12:11
I've a feeling you've recently changed something that might affect this, @EduardMe. Could you please comment?

**Comment by EduardMe** [comment] 2022-06-22 14:38
Yes! There was some timing problem with changing content in the editor
(typing the /command) and writing something to a file via Note. That
happened almost at the same time and so the change was not registered.
Should be working now. I could run the plugin code and see the changes
right away.

**Closed** 2022-06-28 20:21 UTC
Labels: bug, API

**Comment by EduardMe** [comment] 2022-10-11 06:54
I couldn‘t reproduce this issue yet. Can you reproduce this with a few
lines of a code-snippet? And you need to run Editor.updateParagraph if you
want to see the changes immediately (in the Editor).

As I understood, the issue is that updateParagraph doesn‘t update the
Editor content right away? Editor.note.updateParagraph would update the
note content which gets picked up by the Editor after a delay.
